apiVersion: apps/v1
kind: Deployment
metadata:
  name: p4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p4
  template:
    metadata:
      labels:
        app: p4
    spec:
      containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
        name: p4
        ports:
        - containerPort: 80
